# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build-and-test:

    macos:
      xcode: 11.3.1
    environment:
      RVM_VERSION: 2.6.3

    steps:
      - checkout
      -run: 
        name: Setup rvm
        command: rvm install $RVM_VERSION && rvm use $RVM_VERSION && ruby --version
      - run: gem update bundler
      - run: bundle install --without=documentation
      - run:
        name: Validate podspec
        command: bundle exec pod lib lint --skip-tests --allow-warnings
      - run:
        name: Danger
        command: bundle exec danger --remove-previous-comments
