#if !canImport(ObjectiveC)
import XCTest

extension FigmaGenToolsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FigmaGenToolsTests = [
        ("testExample", testExample)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(FigmaGenToolsTests.__allTests__FigmaGenToolsTests)
    ]
}
#endif
