base:
  accessToken: 25961-4ac9fbc9-3bd8-4c43-bbe2-95e477f8a067

colorStyles:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=91%3A3
  assets: FigmaGenDemo/Resources/Colors.xcassets
  destination: FigmaGenDemo/Generated/ColorStyle.swift
  templateOptions:
    publicAccess: true

textStyles:
  file:
    key: 61xw2FQn61Xr7VVFYwiHHy
    includedNodes:
      - 91%3A38
  destination: FigmaGenDemo/Generated/TextStyle.swift
  templateOptions:
    publicAccess: true
    usingSystemFonts: false

images:
  file: 
    key: W6dy4CFSZWUVpVnSzNZIxA
    includeNodes:
      - 92%106
      - 92%242
  assets: FigmaGenDemo/Resources/Images.xcassets/Generated
  destination: FigmaGenDemo/Generated/Images.swift
  templateOptions:
    publicAccess: true

shadowStyles:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=236%3A4
  destination: FigmaGenDemo/Generated/ShadowStyle.swift
  templateOptions:
    publicAccess: true

tokens:
  file: https://www.figma.com/file/W6dy4CFSZWUVpVnSzNZIxA/FigmaGen-Tokens-Demo
  templates:
    colors:
      destination: FigmaGenDemo/Generated/ColorTokens.swift
      templateOptions:
        publicAccess: true
    baseColors:
      destination: FigmaGenDemo/Generated/BaseColorTokens.swift
      templateOptions:
        publicAccess: true
    fontFamilies:
      destination: FigmaGenDemo/Generated/FontFamilyTokens.swift
      templateOptions:
        publicAccess: true
    typographies:
      destination: FigmaGenDemo/Generated/TypographyTokens.swift
      templateOptions:
        publicAccess: true
        styleTypeName: Typography
    boxShadows:
      destination: FigmaGenDemo/Generated/BoxShadowTokens.swift
      templateOptions:
        publicAccess: true
        shadowTypeName: ShadowToken
    spacing:
      destination: FigmaGenDemo/Generated/SpacingTokens.swift
      templateOptions:
        publicAccess: true
    theme:
      destination: FigmaGenDemo/Generated/Theme.swift
      templateOptions:
        publicAccess: true
        shadowTypeName: ShadowToken
