base:
  accessToken: 25961-4ac9fbc9-3bd8-4c43-bbe2-95e477f8a067

colorStyles:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=91%3A3
  assets: FigmaGenDemo/Resources/Colors.xcassets
  destination: FigmaGenDemo/Generated/ColorStyle.swift
  templateOptions:
    publicAccess: true

textStyles:
  file:
    key: 61xw2FQn61Xr7VVFYwiHHy
    includedNodes:
      - 91%3A38
  destination: FigmaGenDemo/Generated/TextStyle.swift
  templateOptions:
    publicAccess: true
    usingSystemFonts: false

images:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=91%3A63
  assets: FigmaGenDemo/Resources/Images.xcassets/Generated
  destination: FigmaGenDemo/Generated/Images.swift
  templateOptions:
    publicAccess: true

shadowStyles:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=236%3A4
  destination: FigmaGenDemo/Generated/ShadowStyle.swift
  templateOptions:
    publicAccess: true
