#if !canImport(ObjectiveC)
import XCTest

extension FigmaGenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FigmaGenTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FigmaGenTests.__allTests__FigmaGenTests),
    ]
}
#endif
