name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Swift Action
      uses: TG908/setup-swift@v1.0.1
      with:
        version: 5.1.3

    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.6.3
          
    - name: Setup bundle
      run: gem update bundler && bundle install --without=documentation
      
    - name: Validate podspec
      run: bundle exec pod lib lint --skip-tests
      
    - name: Run tests
      run: swift test -v
      
    - name: Danger
      run: bundle exec danger --remove-previous-comments
